import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Generated from the folder structure under docs/; order pages with `sidebar_position`.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
